apiVersion: cluster.kupenstack.io/v1alpha1
kind: OOKCluster
metadata:
  name: ookcluster-sample
spec:
  profile: sample-profile.default
  # nodes:
  #   - name: mytestnodename
  #     profile: sample-profile.default
